# Generated by Django 3.2.9 on 2022-02-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_quizquestion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_title',
            field=models.TextField(null=True),
        ),
    ]
